### ISSUE TITLE
ExecuteScript doesn't work

### ISSUE THREAD

**Issue by NoguchiMasafumi** [er-ri/selenium-wrapper-vba#15]
This wrapper is very helpful! Thank you so much!
However, if I use
driver.ExecuteScript
it didn't work.  That Error msg is  Subscript out of range.
I want to get outerHTML. My Code is this.

    DRIVER.Chrome ("C:\Users\" & CreateObject("WScript.Network").UserName & "\Documents\chromedriver\chromedriver.exe")
    DRIVER.OpenBrowser
        DRIVER.NavigateTo "https://hoge"

        '*********************************************
        DRIVER.ExecuteScript ("alert('Hello world!');")
        '*********************************************

        'Work
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetText
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("class")
        'sss = DRIVER.GetPageSource
        
        'Err
        'sss = DRIVER.FindElements(By.tagName, "div")(0).innerHTML
        'sss = DRIVER.FindElements(By.tagName, "div")(0).outerHTML
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetHTML
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetHtml
        'sss = DRIVER.FindElements(By.tagName, "div")(0).value
        'sss = DRIVER.FindElements(By.tagName, "div")(0).Values
        'sss = DRIVER.ExecuteScript("return document.getElementsByTagName('body')[0].outerHTML")
        'sss = DRIVER.ExecuteScript("let ss=1")
        'DRIVER.ExecuteScript ("alert(""ww"")")
        'DRIVER.ExecuteScript "let sss=1"
        'DRIVER.DismissAlert
        'Dim result As Long
        'result = DRIVER.ExecuteScript("let result = arguments[0] + arguments[1];return result;", 1, 2)
        'Debug.Print result  ' 3
        
        'Null
        '***** This line is my purpose. Why Null? *******
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("outerHTML")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("html")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("HTML")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("outerhtml")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("outerHtml")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("div")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("source")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("nodeValue")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("body")
        'sss = DRIVER.FindElements(By.tagName, "div")(0).GetAttribute("document")
        'sss = DRIVER.FindElements(By.tagName, "body")(0).GetAttribute("innerHTML")
        'Set elem1 = DRIVER.FindElements(By.tagName, "div")(0)
        'sss = DRIVER.GetElementAttribute(elem1, "outerHTML")
        

    DRIVER.Quit

**Comment by NoguchiMasafumi** [comment]
#12

**Comment by NoguchiMasafumi** [comment]
I'm so sorry.  It was no good after all.

**Comment by er-ri** [comment]
It's a bug of ExecuteScript when no arguments are passed to the function. @krisk78 

You can get `innerHTML`, `outerHTML` by javascript, try the following code.
`<WebDriver>.ExecuteScript("return arguments[0].innerHTML;", <WebElement>`

**Comment by NoguchiMasafumi** [comment]
Oh! Fantastic!
It worked!! Thank you so much!

        Set elem1 = DRIVER.FindElements(By.tagName, "div")(0)
        sss = DRIVER.ExecuteScript("return arguments[0].outerHTML;", elem1)
