### ISSUE TITLE
FireFox binary

### ISSUE THREAD

**Issue by ImahdiShahidi** [er-ri/selenium-wrapper-vba#16]
Hi
How can i change firefox binay path?
i  have this error:
 exepted browser binary loacation but unable to find binary in defult location

**Comment by er-ri** [comment]
Add `geckodriver.exe` to `Path` or declare as follows
```
driver.Firefox "your\path\to\geckodriver.exe"
```

**Comment by ImahdiShahidi** [comment]
geckodriver cant find firefox.exe 64bit path
i installed firefox 32bit now it ok

**Comment by ImahdiShahidi** [comment]
one more question : can i use chrome/firefox portbale?

**Comment by er-ri** [comment]
what do you mean of portbale(portable)?
