### ISSUE TITLE
access elements in shadow root

### ISSUE THREAD

**Issue by wannesdemaeght** [er-ri/selenium-wrapper-vba#17]
Any way to accomplish this? seems the previous way was to run a javascript on the page, but that does not work anymore?

**Comment by er-ri** [comment]
`Find Element From Shadow Root` and `Find Elements From Shadow Root` have not been implemented. I'm not currently working on this project. If you have time, you can refer [here](https://www.w3.org/TR/webdriver1/#find-element-from-element) and the other codes in `WebDriver.cls` to implement the function by yourself. 

Anyway, using javascript should work. Can you paste you code here?

**Comment by wannesdemaeght** [comment]
Leaving this here for anyone interested:

I wrote a function to get the nth element from the shadowroot.
The shadowroot itself was seemingly impossible to return...

```
Function shadowRoot(shadowHost As Object, Optional child As Long = 1) As Object
    Dim shadowElements As Object
    
    Set shadowElements = Edge.ExecuteScript("return arguments[0].shadowRoot.querySelectorAll('*');", shadowHost)
    Set shadowRoot = shadowElements(child)
End Function
```

**Comment by NoguchiMasafumi** [comment]
If you have a tag like  "managed-user-profile-notice-app"  and execute the following code:

```
Set elm_mng = DRIVER.FindElements(By.tagName, "managed-user-profile-notice-app")(0)
str_vanl_txt = elm_mng.GetText
str_out_htm  = DRIVER.ExecuteScript("return arguments[0].outerHTML;", elm_mng)
Debug.Print str_vanl_txt
Debug.Print str_out_htm
```

If str_vanl_txt returns text   but str_out_htm is empty, there is a high probability that managed-user-profile-notice-app has a ShadowRoot inside it.
Since I couldn't find a way to get the ShadowRoot itself, I'm reporting that I was able to get it with the following code:

```
Set elm_bod = DRIVER.FindElements(By.tagName, "body")(0)
str_js = ""
str_js = str_js & "const hostElement = document.querySelector('managed-user-profile-notice-app');"
str_js = str_js & "if (hostElement && hostElement.shadowRoot) {"
str_js = str_js & "  const str_txt = hostElement.shadowRoot.innerHTML;"
str_js = str_js & "  return str_txt;"
str_js = str_js & "}"
str_out_htm = DRIVER.ExecuteScript(str_js, elm_bod)
Debug.Print str_out_htm
```
