### ISSUE TITLE
How to set User Profile / User data dir for edge

### ISSUE THREAD

**Issue by shajvarg** [er-ri/selenium-wrapper-vba#3]
Hi,
This is a great wrapper for vba. Thanks for sharing it.

I couldn’t get edge to work with this code using default user profile for edge. It always opens a temporary user profile in temp directory.

 In chrome, addarguments works well. 
 I tried the capabilities options but was not successful.
Can you please share some code to use edge with custom user-data-dir?

thanks
Shaju

**Comment by er-ri** [comment]
Hi, Shaju.
I have updated the code to support the arguments option for Edge. Update to the newest version, the following code would work.
```vba
    Set driver = New WebDriver
    Dim edgeOptions As New Options

    driver.Edge
    edgeOptions.BrowserType = Edge
    edgeOptions.EdgeArguments.Add "user-data-dir=C:\\Users\\yourname\\AppData\\Local\\Microsoft\\Edge\\User Data"
    driver.OpenBrowser edgeOptions
    Debug.Print ConvertToJson(driver.Capabilities("capabilities")("msedge")("userDataDir"))
```

**Comment by shajvarg** [comment]
thanks will try it today..

 Meanwhile I did a quick hack code change which also worked in ConstructCapabilities() function

    Case Me.BrowserType = Edge
        Dim edgeOptionsRoot As New Dictionary
        edgeOptionsRoot.Add "args", ChromeArguments
        
        alwaysMatchRoot.Add "browserName", "msedge"
        alwaysMatchRoot.Add "ms:edgeOptions", edgeOptionsRoot
        capabilitiesRoot.Add "alwaysMatch", alwaysMatchRoot

**Comment by er-ri** [comment]
You are right! The updated code were as same as your work. I just set a parameter  `EdgeArguments` for Edge in `Options.cls`.

**Comment by shajvarg** [comment]
Thanks,

I had few more issues..

1)
how to send keys like "RETURN" 
in selenium we have a Keys class for it

I went through the code,, 
ElementSendKeys it appears can only send text

2) how to hide the webdriver window? is there any option to set?

thanks
Shaju

**Comment by er-ri** [comment]
1.
I tried to add those functions, but then I found that JSONConverter.bas cannot handle a single quotation where Keyboard actions are required. For example, you need to send '\uE006' to webdriver for Enter. Some modifications for JSONConverter.bas may be necessary. Do you have any idea to add the feature?

2.
Hiding the window is easy. Just modify vbMinimizedNoFocus to vbHide at WebDriver.cls line 225. But there is a known bug. In some cases, the driver needs to be closed by the user manually. So I kept the window visible.

**Comment by shajvarg** [comment]
1. Yes it appears difficult. will search for solution. Meanwhile I am clicking the button after sending text for now.
2. Right .. just saw the code.. changed to vbhide.
3.  Had another query... I am trying to change the webdriver implicit timeout while running different sections of code using
driver.SetTimeouts , , 20000
driver.SetTimeouts , , 500
this will work? right?

thanks
shaju

**Comment by er-ri** [comment]
It should work.

**Comment by shajvarg** [comment]
thanks, it appears to work in my code.
