### ISSUE TITLE
Error: "EDGE_IDENTITY: get Default OS Account failed"

### ISSUE THREAD

**Issue by derekholtham** [er-ri/selenium-wrapper-vba#4]
Hi

Many thanks for this very useful wrapper for vba/selenium.

I've used the wrapper in an Access application that opens 2 browser sessions in quick succession.

Usually my code works fine, but the first time I run it in every Windows session (I think that is the common denominator!), an error is thrown whilst opening the second browser session: "Run-time error ‘-2147012866 (80072efe)’: The connection with the server was terminated abnormally"

My code is:

Public Sub OpenURL(myPageURL As String)
    
    Dim EdgeDriver As WebDriver
    
    'Create new Edge instance
    Set EdgeDriver = New WebDriver

    With EdgeDriver
      .Edge
      .OpenBrowser
      'Load required webpage
      If LoadWebPage(EdgeDriver, myPageURL) = False Then
        'page wasn't loaded
        MsgBox "Couldn't open page " & myPageURL
      End If
      .CloseBrowser
      .Quit
    End With
    Set EdgeDriver = Nothing

End Sub

The error occurs at the line 'xmlHttp.Send JsonConverter.ConvertToJson(requestBody)' in the Function SendCommand2Webdriver in the WebDriver class module, which is called via the line '.OpenBrowser', just after the previous line (.Edge) opens up a new Edge browser window.

A DOS-like window opens up (entitled C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe) and displays the following information:

> _DevTools listening on ws://127.0.0.1:59773/devtools/browser/15690a75-a9fe-480d-80cb-a4da0ed0cba0
> [12320:7688:0918/154337.511:ERROR:edge_auth_errors.cc(415)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:
> 
> [12320:11368:0918/154506.348:ERROR:util.cc(135)] Can't create base directory: C:\Program Files\Microsoft\EdgeUpdater
> [10368:444:0918/154537.591:ERROR:gpu_init.cc(500)] Passthrough is not supported, GL is disabled, ANGLE is_

Googling this issue has shown up some similar instances of this problem experienced in other languages, (e.g. https://github.com/aerokube/selenoid/issues/986). The suggested solution was to amke sure that you have the line 'driver.quit()' when closing the first instance of Edge that was opened via the WebDriver. However my code definitely includes '.Quit' at the end of the VBA Sub OpenURL.

Any idea how to overcome this problem?

**Comment by er-ri** [comment]
I also encountered this kind of issue. The DOS-like window represents the webdriver msdge's instance. In selenium, when `Quit()` executed or an exception encountered, the driver's instance will be terminated by the program properly. But in vba, `Quit()` or `kill /pid` is not working sometimes. Therefore you may need to close them manually. Unfortunately, I haven't found a solution to solve this issue.

**Comment by shajvarg** [comment]
We can try using Taskkill /f /im drivername.exe in the code using Shell
this always kills all/multiple processes of the exe

**Comment by derekholtham** [comment]
Many thanks for the prompt responses @er-ri and @shajvarg. Will try using Taskkill as suggested.

**Comment by derekholtham** [comment]
Now tested and Taskkill seems to do the trick nicely - thanks again @shajvarg and @er-ri.
