### ISSUE TITLE
Select by value

### ISSUE THREAD

**Issue by krisk78** [er-ri/selenium-wrapper-vba#7]
Hello,

Thank you very much for your great work!

How can we select an item of a listbox ?

I previously used SeleniumBasic [https://github.com/florentbr/SeleniumBasic](url) that implemented a WebElement's method AsSelect.SelectByValue for this usage.

Thanks for your help.

**Comment by taylor8294** [comment]
I would do something like
`driver.FindElement(By.CSS, "[value='my_val']").Click`

**Comment by krisk78** [comment]
Hello,
Thank you very much.
Finally I used the method SendKeys with the expected value and it works.
